service: py36

provider:
  name: azure
  runtime: python3.6
  prefix: tmp
  stage: qa
  region: West Europe
  apim: true

plugins:
  - serverless-azure-functions

package:
  exclude:
    - local.settings.json
    - .vscode/**
    - __pycache__/**
    - node_modules/**
    - .python_packages/**
    - env/**
    - .funcignore
    - package.json
    - package-lock.json
    - data.json


functions:
  hello:
    handler: hello
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          authLevel: anonymous